// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nameserver/nameservice.proto

package nameservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistrationRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Types                []string `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{0}
}

func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegistrationRequest) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type RegistrationResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationResponse) Reset()         { *m = RegistrationResponse{} }
func (m *RegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*RegistrationResponse) ProtoMessage()    {}
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{1}
}

func (m *RegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResponse.Unmarshal(m, b)
}
func (m *RegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResponse.Marshal(b, m, deterministic)
}
func (m *RegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResponse.Merge(m, src)
}
func (m *RegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_RegistrationResponse.Size(m)
}
func (m *RegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResponse proto.InternalMessageInfo

func (m *RegistrationResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BrokerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerRequest) Reset()         { *m = BrokerRequest{} }
func (m *BrokerRequest) String() string { return proto.CompactTextString(m) }
func (*BrokerRequest) ProtoMessage()    {}
func (*BrokerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{2}
}

func (m *BrokerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerRequest.Unmarshal(m, b)
}
func (m *BrokerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerRequest.Marshal(b, m, deterministic)
}
func (m *BrokerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerRequest.Merge(m, src)
}
func (m *BrokerRequest) XXX_Size() int {
	return xxx_messageInfo_BrokerRequest.Size(m)
}
func (m *BrokerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerRequest proto.InternalMessageInfo

type BrokerInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerInfo) Reset()         { *m = BrokerInfo{} }
func (m *BrokerInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerInfo) ProtoMessage()    {}
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{3}
}

func (m *BrokerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerInfo.Unmarshal(m, b)
}
func (m *BrokerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerInfo.Marshal(b, m, deterministic)
}
func (m *BrokerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerInfo.Merge(m, src)
}
func (m *BrokerInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerInfo.Size(m)
}
func (m *BrokerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerInfo proto.InternalMessageInfo

func (m *BrokerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type HeartbeatRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{4}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db68d7a6ab0e12c5, []int{5}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegistrationRequest)(nil), "nameservice.RegistrationRequest")
	proto.RegisterType((*RegistrationResponse)(nil), "nameservice.RegistrationResponse")
	proto.RegisterType((*BrokerRequest)(nil), "nameservice.BrokerRequest")
	proto.RegisterType((*BrokerInfo)(nil), "nameservice.BrokerInfo")
	proto.RegisterType((*HeartbeatRequest)(nil), "nameservice.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "nameservice.HeartbeatResponse")
}

func init() { proto.RegisterFile("nameserver/nameservice.proto", fileDescriptor_db68d7a6ab0e12c5) }

var fileDescriptor_db68d7a6ab0e12c5 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x5d, 0x3b, 0xfc, 0xe8, 0x95, 0xa9, 0xcb, 0x06, 0x96, 0xa2, 0x52, 0xf3, 0x30, 0xf6, 0x62,
	0x0b, 0xfa, 0x0f, 0x06, 0x8a, 0x82, 0x08, 0xc6, 0x37, 0xdf, 0xd2, 0xe5, 0xba, 0x65, 0xda, 0xa6,
	0x26, 0x99, 0xe0, 0x7f, 0xf7, 0x41, 0x5c, 0xd6, 0xd1, 0x8e, 0x6d, 0x6f, 0xb9, 0xf7, 0x9e, 0x7b,
	0xce, 0xc9, 0xe1, 0xc2, 0x79, 0xc1, 0x73, 0x34, 0xa8, 0xbf, 0x51, 0xa7, 0xd5, 0x53, 0x8e, 0x31,
	0x29, 0xb5, 0xb2, 0x8a, 0x1c, 0xd5, 0x5a, 0xf4, 0x0e, 0x7a, 0x0c, 0x27, 0xd2, 0x58, 0xcd, 0xad,
	0x54, 0x05, 0xc3, 0xaf, 0x39, 0x1a, 0x4b, 0x42, 0x38, 0xe0, 0x42, 0x68, 0x34, 0x26, 0xf4, 0x62,
	0x6f, 0x18, 0xb0, 0xaa, 0x24, 0x7d, 0xd8, 0xb3, 0x3f, 0x25, 0x9a, 0xd0, 0x8f, 0xdb, 0xc3, 0x80,
	0xb9, 0x82, 0x0e, 0xa0, 0xdf, 0xa4, 0x31, 0xa5, 0x2a, 0x0c, 0x92, 0x63, 0xf0, 0xa5, 0x58, 0x50,
	0xb4, 0x99, 0x2f, 0x05, 0x3d, 0x81, 0xce, 0x48, 0xab, 0x0f, 0xd4, 0x4b, 0x21, 0x3a, 0x00, 0x70,
	0x8d, 0xc7, 0xe2, 0x5d, 0x6d, 0x97, 0xa5, 0x14, 0x4e, 0x1f, 0x90, 0x6b, 0x9b, 0x21, 0xb7, 0x95,
	0xc9, 0x75, 0xf2, 0x1e, 0x74, 0x6b, 0x18, 0xe7, 0xe0, 0xe6, 0xd7, 0x83, 0xae, 0x53, 0x78, 0xe6,
	0x39, 0xbe, 0xba, 0x6f, 0x93, 0x17, 0x38, 0x74, 0x7e, 0x51, 0x93, 0x38, 0xa9, 0x67, 0xb4, 0x21,
	0x8d, 0xe8, 0x6a, 0x07, 0xc2, 0xc9, 0xd0, 0x16, 0x79, 0x82, 0x60, 0xa5, 0x4e, 0x2e, 0x1a, 0x1b,
	0xeb, 0xce, 0xa3, 0xcb, 0x6d, 0xe3, 0x15, 0xdb, 0x3d, 0x74, 0x96, 0x60, 0x67, 0x9e, 0x44, 0x8d,
	0x95, 0x46, 0x88, 0xd1, 0xd9, 0x86, 0xd9, 0x7f, 0x9e, 0xb4, 0x35, 0xa2, 0x6f, 0xf1, 0x44, 0xda,
	0xe9, 0x3c, 0x4b, 0xc6, 0x2a, 0x4f, 0x67, 0xd7, 0x53, 0x3e, 0x4b, 0x33, 0xf1, 0x59, 0x3f, 0x8b,
	0x6c, 0x7f, 0x71, 0x17, 0xb7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x75, 0x78, 0x34, 0x37,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerNameServiceClient is the client API for BrokerNameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerNameServiceClient interface {
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	RequestBroker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerInfo, error)
}

type brokerNameServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerNameServiceClient(cc *grpc.ClientConn) BrokerNameServiceClient {
	return &brokerNameServiceClient{cc}
}

func (c *brokerNameServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, "/nameservice.BrokerNameService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerNameServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/nameservice.BrokerNameService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerNameServiceClient) RequestBroker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerInfo, error) {
	out := new(BrokerInfo)
	err := c.cc.Invoke(ctx, "/nameservice.BrokerNameService/RequestBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerNameServiceServer is the server API for BrokerNameService service.
type BrokerNameServiceServer interface {
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	RequestBroker(context.Context, *BrokerRequest) (*BrokerInfo, error)
}

func RegisterBrokerNameServiceServer(s *grpc.Server, srv BrokerNameServiceServer) {
	s.RegisterService(&_BrokerNameService_serviceDesc, srv)
}

func _BrokerNameService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerNameServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nameservice.BrokerNameService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerNameServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerNameService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerNameServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nameservice.BrokerNameService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerNameServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerNameService_RequestBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerNameServiceServer).RequestBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nameservice.BrokerNameService/RequestBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerNameServiceServer).RequestBroker(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerNameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nameservice.BrokerNameService",
	HandlerType: (*BrokerNameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _BrokerNameService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _BrokerNameService_Heartbeat_Handler,
		},
		{
			MethodName: "RequestBroker",
			Handler:    _BrokerNameService_RequestBroker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nameserver/nameservice.proto",
}
