// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker_comm/broker_comm.proto

package broker_comm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import result "github.com/j-haj/bdl/result"
import task "github.com/j-haj/bdl/task"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AvailabilityInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Available            bool     `protobuf:"varint,2,opt,name=available" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailabilityInfo) Reset()         { *m = AvailabilityInfo{} }
func (m *AvailabilityInfo) String() string { return proto.CompactTextString(m) }
func (*AvailabilityInfo) ProtoMessage()    {}
func (*AvailabilityInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{0}
}
func (m *AvailabilityInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailabilityInfo.Unmarshal(m, b)
}
func (m *AvailabilityInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailabilityInfo.Marshal(b, m, deterministic)
}
func (dst *AvailabilityInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailabilityInfo.Merge(dst, src)
}
func (m *AvailabilityInfo) XXX_Size() int {
	return xxx_messageInfo_AvailabilityInfo.Size(m)
}
func (m *AvailabilityInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailabilityInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AvailabilityInfo proto.InternalMessageInfo

func (m *AvailabilityInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AvailabilityInfo) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type AvailabilityResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailabilityResponse) Reset()         { *m = AvailabilityResponse{} }
func (m *AvailabilityResponse) String() string { return proto.CompactTextString(m) }
func (*AvailabilityResponse) ProtoMessage()    {}
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{1}
}
func (m *AvailabilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailabilityResponse.Unmarshal(m, b)
}
func (m *AvailabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailabilityResponse.Marshal(b, m, deterministic)
}
func (dst *AvailabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailabilityResponse.Merge(dst, src)
}
func (m *AvailabilityResponse) XXX_Size() int {
	return xxx_messageInfo_AvailabilityResponse.Size(m)
}
func (m *AvailabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvailabilityResponse proto.InternalMessageInfo

type ConnectionRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{2}
}
func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(dst, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ConnectionResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{3}
}
func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(dst, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DisconnectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{4}
}
func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (dst *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(dst, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

type DisconnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{5}
}
func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (dst *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(dst, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

type ProcessResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessResponse) Reset()         { *m = ProcessResponse{} }
func (m *ProcessResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessResponse) ProtoMessage()    {}
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{6}
}
func (m *ProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessResponse.Unmarshal(m, b)
}
func (m *ProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessResponse.Marshal(b, m, deterministic)
}
func (dst *ProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessResponse.Merge(dst, src)
}
func (m *ProcessResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessResponse.Size(m)
}
func (m *ProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessResponse proto.InternalMessageInfo

type ShareRequest struct {
	OriginatorId         int64      `protobuf:"varint,1,opt,name=originator_id,json=originatorId" json:"originator_id,omitempty"`
	OriginatorAddress    string     `protobuf:"bytes,2,opt,name=originator_address,json=originatorAddress" json:"originator_address,omitempty"`
	Task                 *task.Task `protobuf:"bytes,3,opt,name=task" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ShareRequest) Reset()         { *m = ShareRequest{} }
func (m *ShareRequest) String() string { return proto.CompactTextString(m) }
func (*ShareRequest) ProtoMessage()    {}
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{7}
}
func (m *ShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareRequest.Unmarshal(m, b)
}
func (m *ShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareRequest.Marshal(b, m, deterministic)
}
func (dst *ShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareRequest.Merge(dst, src)
}
func (m *ShareRequest) XXX_Size() int {
	return xxx_messageInfo_ShareRequest.Size(m)
}
func (m *ShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareRequest proto.InternalMessageInfo

func (m *ShareRequest) GetOriginatorId() int64 {
	if m != nil {
		return m.OriginatorId
	}
	return 0
}

func (m *ShareRequest) GetOriginatorAddress() string {
	if m != nil {
		return m.OriginatorAddress
	}
	return ""
}

func (m *ShareRequest) GetTask() *task.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type ShareResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareResponse) Reset()         { *m = ShareResponse{} }
func (m *ShareResponse) String() string { return proto.CompactTextString(m) }
func (*ShareResponse) ProtoMessage()    {}
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_broker_comm_604978bab0384fec, []int{8}
}
func (m *ShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareResponse.Unmarshal(m, b)
}
func (m *ShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareResponse.Marshal(b, m, deterministic)
}
func (dst *ShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareResponse.Merge(dst, src)
}
func (m *ShareResponse) XXX_Size() int {
	return xxx_messageInfo_ShareResponse.Size(m)
}
func (m *ShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareResponse proto.InternalMessageInfo

func (m *ShareResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*AvailabilityInfo)(nil), "AvailabilityInfo")
	proto.RegisterType((*AvailabilityResponse)(nil), "AvailabilityResponse")
	proto.RegisterType((*ConnectionRequest)(nil), "ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "ConnectionResponse")
	proto.RegisterType((*DisconnectRequest)(nil), "DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "DisconnectResponse")
	proto.RegisterType((*ProcessResponse)(nil), "ProcessResponse")
	proto.RegisterType((*ShareRequest)(nil), "ShareRequest")
	proto.RegisterType((*ShareResponse)(nil), "ShareResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InterBrokerCommClient is the client API for InterBrokerComm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InterBrokerCommClient interface {
	// SendAvailability communicates a brokers availability for additional tasks.
	// It is used to be send and retract availability.
	SendAvailability(ctx context.Context, in *AvailabilityInfo, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// Connect establishes a link between two brokers, allowing them to share
	// work.
	Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	// Disconnect can be called by a broker to terminate a connection with a linked broker.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// ShareTask sends a task to a linked broker.
	ShareTask(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	// ProcessResult either sends the result to the model or sends the result on to the
	// next broker.
	ProcessResult(ctx context.Context, in *result.Result, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type interBrokerCommClient struct {
	cc *grpc.ClientConn
}

func NewInterBrokerCommClient(cc *grpc.ClientConn) InterBrokerCommClient {
	return &interBrokerCommClient{cc}
}

func (c *interBrokerCommClient) SendAvailability(ctx context.Context, in *AvailabilityInfo, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, "/InterBrokerComm/SendAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBrokerCommClient) Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, "/InterBrokerComm/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBrokerCommClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/InterBrokerComm/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBrokerCommClient) ShareTask(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, "/InterBrokerComm/ShareTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interBrokerCommClient) ProcessResult(ctx context.Context, in *result.Result, opts ...grpc.CallOption) (*ProcessResponse, error) {
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, "/InterBrokerComm/ProcessResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterBrokerCommServer is the server API for InterBrokerComm service.
type InterBrokerCommServer interface {
	// SendAvailability communicates a brokers availability for additional tasks.
	// It is used to be send and retract availability.
	SendAvailability(context.Context, *AvailabilityInfo) (*AvailabilityResponse, error)
	// Connect establishes a link between two brokers, allowing them to share
	// work.
	Connect(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	// Disconnect can be called by a broker to terminate a connection with a linked broker.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// ShareTask sends a task to a linked broker.
	ShareTask(context.Context, *ShareRequest) (*ShareResponse, error)
	// ProcessResult either sends the result to the model or sends the result on to the
	// next broker.
	ProcessResult(context.Context, *result.Result) (*ProcessResponse, error)
}

func RegisterInterBrokerCommServer(s *grpc.Server, srv InterBrokerCommServer) {
	s.RegisterService(&_InterBrokerComm_serviceDesc, srv)
}

func _InterBrokerComm_SendAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailabilityInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBrokerCommServer).SendAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterBrokerComm/SendAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBrokerCommServer).SendAvailability(ctx, req.(*AvailabilityInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBrokerComm_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBrokerCommServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterBrokerComm/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBrokerCommServer).Connect(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBrokerComm_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBrokerCommServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterBrokerComm/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBrokerCommServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBrokerComm_ShareTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBrokerCommServer).ShareTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterBrokerComm/ShareTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBrokerCommServer).ShareTask(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterBrokerComm_ProcessResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(result.Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterBrokerCommServer).ProcessResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InterBrokerComm/ProcessResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterBrokerCommServer).ProcessResult(ctx, req.(*result.Result))
	}
	return interceptor(ctx, in, info, handler)
}

var _InterBrokerComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "InterBrokerComm",
	HandlerType: (*InterBrokerCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAvailability",
			Handler:    _InterBrokerComm_SendAvailability_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _InterBrokerComm_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _InterBrokerComm_Disconnect_Handler,
		},
		{
			MethodName: "ShareTask",
			Handler:    _InterBrokerComm_ShareTask_Handler,
		},
		{
			MethodName: "ProcessResult",
			Handler:    _InterBrokerComm_ProcessResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker_comm/broker_comm.proto",
}

func init() {
	proto.RegisterFile("broker_comm/broker_comm.proto", fileDescriptor_broker_comm_604978bab0384fec)
}

var fileDescriptor_broker_comm_604978bab0384fec = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x93, 0x0c, 0x62, 0xa6, 0x97, 0x49, 0xdb, 0xdc, 0x0c, 0x28, 0x8a, 0xf8, 0xa9, 0x0c,
	0x8b, 0x2e, 0x18, 0x57, 0x9a, 0x41, 0x62, 0x87, 0x54, 0xca, 0xa6, 0xac, 0x50, 0xca, 0xbe, 0x72,
	0x13, 0x03, 0x56, 0x12, 0xbb, 0xd8, 0x2e, 0x12, 0x5b, 0x5e, 0x85, 0x17, 0x45, 0x75, 0x52, 0x12,
	0xda, 0xb2, 0x49, 0xe2, 0x93, 0xa3, 0xfb, 0xf3, 0x1d, 0xc3, 0xb3, 0x8d, 0x56, 0x25, 0xd7, 0xeb,
	0x5c, 0xd5, 0xf5, 0xac, 0xf7, 0x4d, 0xb7, 0x5a, 0x59, 0x95, 0xc6, 0x9a, 0x9b, 0x5d, 0x65, 0x67,
	0xcd, 0xab, 0x15, 0x47, 0x96, 0x99, 0x72, 0xb6, 0x7f, 0x34, 0x02, 0xf9, 0x08, 0xe3, 0xf9, 0x0f,
	0x26, 0x2a, 0xb6, 0x11, 0x95, 0xb0, 0x3f, 0x97, 0xf2, 0x8b, 0xc2, 0x04, 0x2e, 0x59, 0x51, 0x68,
	0x6e, 0x4c, 0xe2, 0x4f, 0xfc, 0xe9, 0x20, 0x3b, 0x1c, 0xf1, 0x29, 0x0c, 0x58, 0xe3, 0xae, 0x78,
	0x12, 0x4c, 0xfc, 0xe9, 0x55, 0xd6, 0x09, 0xe4, 0x09, 0xdc, 0xf4, 0x6b, 0x65, 0xdc, 0x6c, 0x95,
	0x34, 0x9c, 0xdc, 0x42, 0xb4, 0x50, 0x52, 0xf2, 0xdc, 0x0a, 0x25, 0x33, 0xfe, 0x7d, 0xc7, 0x8d,
	0xfd, 0x7f, 0x13, 0xf2, 0x0a, 0xb0, 0x6f, 0x6f, 0x8a, 0xe0, 0x10, 0x02, 0x55, 0x3a, 0xeb, 0x55,
	0x16, 0xa8, 0x92, 0xc4, 0x10, 0x7d, 0x10, 0x26, 0x6f, 0x8c, 0x6d, 0x51, 0x72, 0x03, 0xd8, 0x17,
	0xdb, 0xfe, 0x11, 0x8c, 0x3e, 0x69, 0x95, 0x73, 0x63, 0xfe, 0x4a, 0xbf, 0x7c, 0xb8, 0x5e, 0x7d,
	0x63, 0x9a, 0x1f, 0xc6, 0x79, 0x09, 0xa1, 0xd2, 0xe2, 0xab, 0x90, 0xcc, 0x2a, 0xbd, 0x16, 0x85,
	0xeb, 0x74, 0x91, 0x5d, 0x77, 0xe2, 0xb2, 0xc0, 0x5b, 0xc0, 0x9e, 0xe9, 0x30, 0x7e, 0xe0, 0xc6,
	0x8f, 0xba, 0x3f, 0xf3, 0x96, 0xd6, 0x73, 0x78, 0xb0, 0x27, 0x9d, 0x5c, 0x4c, 0xfc, 0xe9, 0xa3,
	0x3b, 0xa0, 0x0e, 0xfb, 0x67, 0x66, 0xca, 0xcc, 0xe9, 0xe4, 0x05, 0x84, 0xed, 0x0c, 0xe7, 0x77,
	0xbc, 0xfb, 0x1d, 0xc0, 0x68, 0x29, 0x2d, 0xd7, 0xef, 0x5d, 0xba, 0x0b, 0x55, 0xd7, 0xf8, 0x0e,
	0xc6, 0x2b, 0x2e, 0x8b, 0x3e, 0x68, 0x8c, 0xe8, 0x71, 0x86, 0xe9, 0x63, 0x7a, 0x36, 0x0a, 0x0f,
	0xdf, 0xc0, 0x65, 0x4b, 0x17, 0x91, 0x9e, 0xc4, 0x92, 0xc6, 0xf4, 0x94, 0x3d, 0xf1, 0xf0, 0x2d,
	0x40, 0x07, 0x16, 0x91, 0x9e, 0xa0, 0x4f, 0x63, 0x7a, 0x86, 0xbc, 0x87, 0xaf, 0x61, 0xe0, 0x76,
	0xdc, 0xaf, 0x8d, 0x21, 0xed, 0x33, 0x4f, 0x87, 0xf4, 0x9f, 0xf5, 0x89, 0x87, 0xf7, 0x10, 0x76,
	0x49, 0xed, 0x2a, 0x8b, 0x43, 0xda, 0x5e, 0xdf, 0xe6, 0x9c, 0x8e, 0xe9, 0x71, 0x92, 0xde, 0xe6,
	0xa1, 0xbb, 0xc9, 0xf7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36, 0x87, 0x6a, 0x2f, 0x10, 0x03,
	0x00, 0x00,
}
