// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task/task.proto

package task // import "github.com/j-haj/bdl/task"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	TaskObj              []byte   `protobuf:"bytes,3,opt,name=task_obj,json=taskObj,proto3" json:"task_obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_1a2f520eee1742fb, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Task) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Task) GetTaskObj() []byte {
	if m != nil {
		return m.TaskObj
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
}

func init() { proto.RegisterFile("task/task.proto", fileDescriptor_task_1a2f520eee1742fb) }

var fileDescriptor_task_1a2f520eee1742fb = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2c, 0xce,
	0xd6, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x52, 0x10, 0x17,
	0x4b, 0x48, 0x62, 0x71, 0xb6, 0x90, 0x38, 0x17, 0x3b, 0x88, 0x1f, 0x9f, 0x99, 0x22, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x06, 0xe2, 0x7a, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0x15, 0xe7, 0x97,
	0x16, 0x25, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x92, 0x5c, 0x1c,
	0x60, 0x0d, 0xf9, 0x49, 0x59, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0x03, 0xfc, 0x93,
	0xb2, 0x9c, 0xa4, 0xa3, 0x24, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0xb3, 0x74, 0x33, 0x12, 0xb3, 0xf4, 0x93, 0x52, 0x72, 0xc0, 0x96, 0x27, 0xb1, 0x81, 0x6d, 0x37,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x77, 0xde, 0x92, 0x90, 0x00, 0x00, 0x00,
}
