# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_service/model_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from task_service import task_service_pb2 as task__service_dot_task__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_service/model_service.proto',
  package='model_service',
  syntax='proto3',
  serialized_options=_b('Z\"github.com/j-haj/bdl/model_service'),
  serialized_pb=_b('\n!model_service/model_service.proto\x12\rmodel_service\x1a\x1ftask_service/task_service.proto\"&\n\x13RegistrationRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x16\n\x14RegistrationResponse\"\x0e\n\x0cSendResponse2\xa9\x01\n\x0cModelService\x12Z\n\rRegisterModel\x12\".model_service.RegistrationRequest\x1a#.model_service.RegistrationResponse\"\x00\x12=\n\x08SendTask\x12\x12.task_service.Task\x1a\x1b.model_service.SendResponse\"\x00\x42$Z\"github.com/j-haj/bdl/model_serviceb\x06proto3')
  ,
  dependencies=[task__service_dot_task__service__pb2.DESCRIPTOR,])




_REGISTRATIONREQUEST = _descriptor.Descriptor(
  name='RegistrationRequest',
  full_name='model_service.RegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='model_service.RegistrationRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=123,
)


_REGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='RegistrationResponse',
  full_name='model_service.RegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=147,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='model_service.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['RegistrationRequest'] = _REGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['RegistrationResponse'] = _REGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONREQUEST,
  __module__ = 'model_service.model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_service.RegistrationRequest)
  ))
_sym_db.RegisterMessage(RegistrationRequest)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONRESPONSE,
  __module__ = 'model_service.model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_service.RegistrationResponse)
  ))
_sym_db.RegisterMessage(RegistrationResponse)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'model_service.model_service_pb2'
  # @@protoc_insertion_point(class_scope:model_service.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)


DESCRIPTOR._options = None

_MODELSERVICE = _descriptor.ServiceDescriptor(
  name='ModelService',
  full_name='model_service.ModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=166,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterModel',
    full_name='model_service.ModelService.RegisterModel',
    index=0,
    containing_service=None,
    input_type=_REGISTRATIONREQUEST,
    output_type=_REGISTRATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendTask',
    full_name='model_service.ModelService.SendTask',
    index=1,
    containing_service=None,
    input_type=task__service_dot_task__service__pb2._TASK,
    output_type=_SENDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVICE)

DESCRIPTOR.services_by_name['ModelService'] = _MODELSERVICE

# @@protoc_insertion_point(module_scope)
